services:
#  nginx:
#      image: nginx:stable-alpine
#      ports:
#        - "8080:80"
#      volumes:
#        - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#        - ./view:/usr/share/nginx/html
#      depends_on:
#        - catalogo_api
#        - usuarios_api
  
  catalogo_api:
    build: ./services/catalogo
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - db

  catalogo_migrator:
    build: ./services/catalogo
    environment:
      DB_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    depends_on:
      - db
    command: ["npm", "run", "migrate:up"]
    
  usuarios_api:
    build: ./services/usuarios
    ports:
      - "3001:3000"
    environment:
      DB_HOST: db
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d


volumes:
  postgres-data: