version: '3.8'

services:
  api:
    build: ./services/catalogo
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_USER: loja
      DB_PASSWORD: 12345
      DB_NAME: lojadecartas
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: loja
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: lojadecartas
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data: