services:
  ### backend ###
  catalogo_api:
    build: ./services/catalogo
    restart: always
    ports:
      - "3000:3000"
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_SSL: ${DB_SSL}

  usuarios_api:
    build: ./services/usuarios
    restart: always
    ports:
      - "3001:3000"
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      DB_SSL: ${DB_SSL}
      CHAVE_MESTRA_LOJA: ${CHAVE_MESTRA_LOJA}

  carrinho_api:
    build: ./services/carrinho
    restart: always
    ports:
      - "3002:3000"
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_SSL: ${DB_SSL}
    depends_on:
      - usuarios_api
      - catalogo_api

  pagamento_api:
    build: ./services/pagamento
    restart: always
    ports:
      - "3003:3000"
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_SSL: ${DB_SSL}
    depends_on:
      - usuarios_api
      - catalogo_api
      - carrinho_api

  ### ferramentas ###
  all_migrations:
    build: ./services/migrator
    profiles: ["tools"]
    environment:
      DB_HOST: ${DB_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DB_SSL: ${DB_SSL}
    command: ["npm", "run", "migrate:up"]
